"""add task priority

Revision ID: b3b232e03cf2
Revises: a6bcd6165982
Create Date: 2026-09-27 01:56:18.056395

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b3b232e03cf2'
down_revision: Union[str, Sequence[str], None] = 'a6bcd6165982'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column(
        "tasks",
        sa.Column("priority", sa.Integer(), nullable=True)
    )

    op.execute(
        "UPDATE tasks SET priority = 1 WHERE priority IS NULL"
    )

    op.alter_column(
        "tasks",
        "priority",
        nullable=False
    )

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'password')
    op.drop_column('users', 'email')
    op.drop_column('tasks', 'priority')
    # ### end Alembic commands ###
